In [1]:
import numpy as np

# ones

In [3]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [6]:
arr = np.ones((4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Zero

In [8]:
arr = np.zeros((4,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# Linspace

In [23]:
arr  = np.linspace(0,30,6)
print(arr)

[ 0.  6. 12. 18. 24. 30.]
