# Identity
Create an identity matrix with specified dimensions.



In [1]:
import numpy as np
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
arr = np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Array of k Random Value
Creates an n-dimensional array of a random value.

In [9]:
arr1 = np.full((5,5),fill_value=8)
print(arr1)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


# Random.random
Generate n random float samples.

In [12]:
arr2  = np.random.random(3)
print(arr2)

[0.78921769 0.23705325 0.51849078]


# Random.randint
Generate n random integer samples within a range.



In [16]:
arr3 = np.random.randint(1,10,5)
print(arr3)

[3 8 9 5 7]


# Uniform Samples
Generate a random sample from a uniform distribution between lower and higher limit values.


np.random.uniform(5,10,size = 4)
array([6.47445571, 5.60725873, 8.82192327, 7.47674099])

In [19]:
arr4 = np.random.uniform(1,5,size = 6)
print(arr4)

[1.97594343 1.78923071 4.74208187 4.71899328 1.15861919 4.31011132]
