# Array Operations

# sum

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(np.sum(a))

21


# Min
Return the minimum value from the array.

In [2]:
a1 = np.array([3,4,7,2,5,3,6])
print(np.min(a1))

2


# Max
Return the maximum value from the array.

In [4]:
a1 = np.array([3,4,7,2,5,3,6])
print(np.min(a1))
print(np.max(a1))

2
7


# argmin
return the position of particular element

In [7]:
a1 = np.array([3,4,7,2,5,3,6])
print(np.min(a1),np.argmin(a1))
print(np.max(a1),np.argmax(a1))

2 3
7 2


# sqrt
return sqrt of array

In [9]:
a2 = np.arange(6)
print(a2)
print(np.sqrt(a2))

[0 1 2 3 4 5]
[0.         1.         1.41421356 1.73205081 2.         2.23606798]


# sin
return sin value of array

In [11]:
np.sin(a2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

# cos 
return cos value of array

In [12]:
a = np.array([1,2,3,4,5,6])
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]


# cumsum

In [16]:
n = np.array([1,2,3,4])
print(np.cumsum(n))

[ 1  3  6 10]


In [14]:
3+3

6