# NumPy – Arithmetic Operations

# Addition

In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

c = a+3
print(a)
print()
print(c)

[1 2 3 4]

[4 5 6 7]


In [2]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
c = a+b
print(c)

[ 7  9 11 13]


In [3]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
c = np.add(a,b)
print(c)

[ 7  9 11 13]


# Subtraction

In [4]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c1 = b - a
print(c1)

[5 2 2 5]


In [5]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c1  = np.subtract(b,a)
print(c1)

[5 2 2 5]


# Multiplication

In [6]:
a = np.array([1,2,3,4])
c2  = a*2
print(c2)

[2 4 6 8]


In [7]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c2 = a*b
print(c2)

[ 6  8 15 36]


In [8]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c2  = np.multiply(a,b)
print(c2)

[ 6  8 15 36]


# Division

In [9]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c3 = b/a
print(c3)

[6.         2.         1.66666667 2.25      ]


In [10]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c3  = np.divide(b,a)
print(c3)

[6.         2.         1.66666667 2.25      ]


# Power

In [11]:
a = np.array([1,2,3,4])
b = np.array([6,4,5,9])
c4  = np.power(b,a)
print(c4)

[   6   16  125 6561]


# Remainder

In [12]:
a = np.array([2,2,3,4])
b = np.array([7,4,5,9])
c5  = np.remainder(b,a)
print(c5)

[1 0 2 1]


# Absolute Values

In [13]:
x = np.array([-1,-2,-4,-6,-8,6,7,8,9])
z = np.absolute(x)
print(z)


[1 2 4 6 8 6 7 8 9]


# 2D Array

In [14]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[6,7,8,9],[1,2,3,4]])
print(a)
print()
print(b)
print()
print(a+b)

[[1 2 3 4]
 [1 2 3 4]]

[[6 7 8 9]
 [1 2 3 4]]

[[ 7  9 11 13]
 [ 2  4  6  8]]


In [15]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[6,7,8,9],[1,2,3,4]])
print(a)
print()
print(b)
print()
print(a-b)

[[1 2 3 4]
 [1 2 3 4]]

[[6 7 8 9]
 [1 2 3 4]]

[[-5 -5 -5 -5]
 [ 0  0  0  0]]


In [16]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[6,7,8,9],[1,2,3,4]])
print(a)
print()
print(b)
print()
print(np.divide(a,b))

[[1 2 3 4]
 [1 2 3 4]]

[[6 7 8 9]
 [1 2 3 4]]

[[0.16666667 0.28571429 0.375      0.44444444]
 [1.         1.         1.         1.        ]]


In [17]:
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[6,7,8,9],[1,2,3,4]])
print(a)
print()
print(b)
print()
print(np.multiply(a,b))

[[1 2 3 4]
 [1 2 3 4]]

[[6 7 8 9]
 [1 2 3 4]]

[[ 6 14 24 36]
 [ 1  4  9 16]]


In [21]:
a = np.array([1,2,3,4])
print(np.min(a),np.argmin(a))
print(np.max(a),np.argmax(a))

1 0
4 3


In [27]:
a = np.array([[7,7,5,3,8],[6,4,8,2,6]])
print(np.min(a,axis = 1))

[3 2]
