# NumPy Array Shape

# Shape of an Array
The shape of an array is the number of elements in each dimension.

In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print()
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


In [4]:
a = np.array([1,2,3,4,5])
print(a)
print()
print(a.shape)

[1 2 3 4 5]

(5,)


In [5]:
a1 = np.array([1,2,3,4,5],ndmin=4)
print(a1)
print()
print(np.ndim(a1))
print()
print(a1.shape)


[[[[1 2 3 4 5]]]]

4

(1, 1, 1, 5)


In [9]:
a2  = np.array([1,2,3,4,5,6,3,4,5])
print(a2)
print(a2.shape)
x = a2.reshape(3,3)
print(x)
print(x.shape)

[1 2 3 4 5 6 3 4 5]
(9,)
[[1 2 3]
 [4 5 6]
 [3 4 5]]
(3, 3)


In [15]:
a3  = np.array([1,2,3,4,5,6,3,4,5,10,11,12])
print(a3)
print(np.ndim(a3))
print(a3.shape)
x1  = a3.reshape(2,3,2)
print(x1)
print(np.ndim(x1))
print(x1.reshape(-1))

[ 1  2  3  4  5  6  3  4  5 10 11 12]
1
(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 3  4]
  [ 5 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  3  4  5 10 11 12]
