# Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.
We pass a sequence of arrays that we want to join to the concatenate() function

In [4]:
import numpy as np


arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [6]:
a  = np.array([22,33,44,55])
b = np.array([66,77,88,99])
c  = np.array([22,33,44,55])
d = np.array([66,77,88,99])
print(np.concatenate((a,b,c,d)))

[22 33 44 55 66 77 88 99 22 33 44 55 66 77 88 99]


# Join two 2-D arrays along rows (axis=0):

In [10]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print()
print(arr2)
print()
print(np.concatenate((arr1,arr2),axis=0))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Join two 2-D arrays along rows (axis=1):

In [11]:
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print()
print(arr2)
print()
print(np.concatenate((arr1,arr2),axis=1))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [14]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)