# NumPy Array Iterating
Iterating means going through elements one by one

In [3]:
import numpy as np

# Iterating 1-D Array

In [5]:
a = np.array([1,2,3,4,3,4,5,6,7,8,9,9])
for i in a:
    print(i)

1
2
3
4
3
4
5
6
7
8
9
9


# Iterating 2-D Arrays

In [8]:
a  = np.array([[1,2,3,4],[5,6,7,8]])
#print(a)
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [9]:
a  = np.array([[1,2,3,4],[5,6,7,8]])
for i in a:
    for x  in i :
        print(x)

1
2
3
4
5
6
7
8


# Iterating 3-D Arrays

In [10]:
c  =  np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [11]:
c  =  np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for i in c:
    print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
c  =  np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for i in c:
    for x in i:
        for y in x:
            print(y)
   

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [15]:
a  = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8


In [16]:
b  = np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(b):
    print(i)

1
2
3
4
5
6
7
8


In [17]:
c  =  np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for i in np.nditer(c):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
