# Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [2]:
import numpy as np

# Split Into Arrays

In [3]:
arr = np.array([1,2,3,4,5,6])
new = np.array_split(arr,3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
arr = np.array([1,2,3,4,5,6])
new = np.array_split(arr,4)
print(new)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [7]:
arr = np.array([1,2,3,4,5,6])
new = np.array_split(arr,3)
print(new[0])
print(new[1])
print(new[2])


[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

In [8]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
new1 = np.array_split(arr,3)
print(new1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [11]:
arr = np.array([[1, 2,3], [3, 4,5], [5,6, 6], [7, 8,8], [9, 8,10], [11, 12,12]])
new2 = np.array_split(arr,3)
print(new2[0])
print()
print(new2[1])
print()
print(new2[2])

[[1 2 3]
 [3 4 5]]

[[5 6 6]
 [7 8 8]]

[[ 9  8 10]
 [11 12 12]]


# hsplit()

In [12]:

arr = np.array([[1, 2,3], [3, 4,5], [5,6, 6], [7, 8,8], [9, 8,10], [11, 12,12]])
new3 = np.hsplit(arr,3)
print(new3)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 8],
       [12]]), array([[ 3],
       [ 5],
       [ 6],
       [ 8],
       [10],
       [12]])]


# vsplit()

In [13]:
arr = np.array([[1, 2,3], [3, 4,5], [5,6, 6], [7, 8,8], [9, 8,10], [11, 12,12]])
new3 = np.vsplit(arr,3)
print(new3)

[array([[1, 2, 3],
       [3, 4, 5]]), array([[5, 6, 6],
       [7, 8, 8]]), array([[ 9,  8, 10],
       [11, 12, 12]])]
