# NumPy Searching Arrays

In [4]:
import numpy as np

In [7]:
a =np.array([1,2,2,3,4,2,5,6,2,7,8,2,4,5,2])
print(a)
b = np.where(a==4)
print(b)

[1 2 2 3 4 2 5 6 2 7 8 2 4 5 2]
(array([ 4, 12], dtype=int64),)


In [9]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c)
d  = np.where(c%2==0)
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
(array([1, 3, 5, 7, 9], dtype=int64),)


In [10]:
f = np.array([1,2,3,4,5,6,7,8,9,10])
print(f)
g  = np.where(f%2==1)
print(g)

[ 1  2  3  4  5  6  7  8  9 10]
(array([0, 2, 4, 6, 8], dtype=int64),)
