# NumPy Sorting Arrays

In [1]:
import numpy as np

In [4]:
a  = np.array([10,8,5,4,7,9,2,6,0,1,3])
print(a)
b = np.sort(a)
print(b)

[10  8  5  4  7  9  2  6  0  1  3]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
a  = np.array([10,8,5,4,7,9,2,6,0,1,3])
print(a)
b = np.sort(a)[::-1]
print(b)

[10  8  5  4  7  9  2  6  0  1  3]
[10  9  8  7  6  5  4  3  2  1  0]


In [6]:
x = np.array(['bannan','mellon','apple','cherry'])
print(x)
print(np.sort(x))

['bannan' 'mellon' 'apple' 'cherry']
['apple' 'bannan' 'cherry' 'mellon']


In [9]:
l = np.array([[3,2,4,5,1],[7,5,6,9,3]])
print(l)
print()
print(np.sort(l))

[[3 2 4 5 1]
 [7 5 6 9 3]]

[[1 2 3 4 5]
 [3 5 6 7 9]]
