# numpy.transpose() in Python

In [1]:
import numpy as np

In [2]:
a  = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
a  = np.arange(12).reshape(3,4)
print(a)
print(np.shape(a))
print()
b = np.transpose(a)
print(b)
print(np.shape(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [7]:
x = np.arange(10)
print(np.transpose(x))

[0 1 2 3 4 5 6 7 8 9]
