# insert

In [1]:
import numpy as np

In [5]:
a  = np.array([1,2,3,4,5])
print(a)
print()
b = np.insert(a , (0,3) , (22,44))
print(b)

[1 2 3 4 5]

[22  1  2  3 44  4  5]


In [11]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
c1 = np.arange(12).reshape(3,4)
print(c1)
print()
x = np.insert(c1 , 0 , 33)
print(x)
print()
x1 = np.insert(c1 , 2 , 99, axis= 1 )
print(x1)
print()
x2 = np.insert(c1 , 2 , ([88,77,66,55]), axis= 0 )
print(x2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[33  0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1 99  2  3]
 [ 4  5 99  6  7]
 [ 8  9 99 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [88 77 66 55]
 [ 8  9 10 11]]


# delete

In [26]:
a  = np.array([1,2,3,4,5])
print(a)
b = np.delete(a,3)
print(b)


[1 2 3 4 5]
[1 2 3 5]


In [33]:
c = np.array([[1,2,3,4],[5,6,7,8],[3,5,7,9]])
print(c)
print()
y = np.delete(c , 0)
print(y)
y1 = np.delete(c , 1 , axis  = 1)
print()
print(y1)

y2 = np.delete(c , 1 , axis  = 0)
print()
print(y2)

[[1 2 3 4]
 [5 6 7 8]
 [3 5 7 9]]

[2 3 4 5 6 7 8 3 5 7 9]

[[1 3 4]
 [5 7 8]
 [3 7 9]]

[[1 2 3 4]
 [3 5 7 9]]
