# NumPy Summations

## Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

## np.add()     np.sum()

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.add(a,b)
print(c)

[ 6  8 10 12]


In [5]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.sum([a,b])
print(c)

36


# Summation Over an Axis
If you specify axis=1, NumPy will sum the numbers in each array.

In [7]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
b1 = np.array([9,10,11,12])
c = np.sum([a,b ,b1],axis = 1)
print(c)

[10 26 42]


# Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [8]:
x = np.array([1,2,3,4])
print(np.cumsum(x))

[ 1  3  6 10]
