# NumPy - Indexing & Slicing In 2D

In [1]:
import numpy as np

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a[:])
print()
print('slicing from starting')
print(a[1:])
print()
print('Gettina column by sclicing')
print(a[... , 1])
print()
print('Gettina row by sclicing')

print(a[2,...])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

slicing from starting
[[4 5 6]
 [7 8 9]]

Gettina column by sclicing
[2 5 8]

Gettina row by sclicing
[7 8 9]
