# NumPy Set Operations

# What is a Set
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

# Create Sets in NumPy
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [7]:
import numpy as np

In [9]:
a  = np.array([1,2,3,4,4,4,4,2,2,2,5,5,5,5,1,1,6,6,6])
b = np.unique(a)
print(b)
print(type(b))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Finding Union
To find the unique values of two arrays, use the union1d() method.

In [10]:
x = np.array([1,2,3,4])
y = np.array([3,4,5,6])
print(np.union1d(x,y))

[1 2 3 4 5 6]


# Finding Intersection
To find only the values that are present in both arrays, use the intersect1d() method

In [11]:
x = np.array([1,2,3,4])
y = np.array([3,4,5,6])
print(np.intersect1d(x,y))

[3 4]


# Finding Difference
To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method

In [13]:
x = np.array([1,2,3,4])
y = np.array([3,4,5,6])
print(np.setdiff1d(x,y))
print(np.setdiff1d(y,x))

[1 2]
[5 6]


# Finding Symmetric Difference
To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [14]:
x = np.array([1,2,3,4])
y = np.array([3,4,5,6])
print(np.setxor1d(x,y))

[1 2 5 6]
