### Create a 2x3 matrix

### Create a 1D array (vector)

### Compute the determinant of a matrix

### system of linear equations Ax = b

### eigenvalues and eigenvectors

### Compute the rank of a matrix

In [5]:

import numpy as np

# Create a 2x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array (vector)
vector = np.array([7, 8, 9])

print("Matrix:")
print(matrix)
print("Vector:")
print(vector)

Matrix:
[[1 2 3]
 [4 5 6]]
Vector:
[7 8 9]


In [7]:
# Compute the determinant of a matrix using np.linalg.det()
a  = np.arange(25).reshape(5,5)
print(a)
det = np.linalg.det(a)
print(det)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
0.0


In [8]:
# Compute eigenvalues and eigenvectors using np.linalg.eig()
eigenvalues ,  eigenvectors =  np.linalg.eig(a)
print('eigenvalues')
print(eigenvalues)
print('eigenvectors')
print(eigenvectors)

eigenvalues
[ 6.39116499e+01 -3.91164992e+00  3.19626490e-15 -1.64396509e-15
  8.90756696e-17]
eigenvectors
[[-0.0851802   0.67779864  0.06945307 -0.39148436 -0.10985832]
 [-0.23825372  0.36348873  0.44032228  0.290592   -0.03338055]
 [-0.39132723  0.04917881 -0.57200489  0.01857127  0.63352165]
 [-0.54440074 -0.2651311  -0.45476933  0.6570189  -0.72746836]
 [-0.69747425 -0.57944101  0.51699887 -0.5746978   0.23718558]]


In [10]:
# Solving a system of linear equations Ax = b
A = np.array([[6,2],[3,8]])
B = np.array([5,6])
C = np.linalg.solve(A,B)
print(C)

[0.66666667 0.5       ]


In [12]:
# Compute the rank of a matrix using np.linalg.matrix_rank()
a
rank = np.linalg.matrix_rank(a)
print(rank)

2
