# Dot and Scalar product 
NumPy, the term "dot product" usually refers to the matrix multiplication between two arrays, while the "scalar product" is the element-wise multiplication of an array with a scalar value. Let's explore both concepts in NumPy

# Dot Product (np.dot or @):
The dot product is used for matrix multiplication between two arrays. For 1-dimensional arrays, it calculates the inner product; for 2-dimensional arrays, it performs matrix multiplication.

In [3]:
import numpy as np
a  = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a,b)
print(c)

d = a@b
print(d)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Scalar Product (Element-wise Multiplication):
Scalar product involves multiplying each element of an array by a scalar value.

In [4]:
x = np.array([1,2,3,4,5,6,7])
scalar = 10
y = x*scalar
print(y)

[10 20 30 40 50 60 70]
